### PR TITLE
Auto close void elements

### PR DESCRIPTION
**Pull request by jessedijkstra**
See http://www.colorglare.com/2014/02/03/to-close-or-not-to-close.html

### CODE REVIEW

**Review by sn3p — DISMISSED** [review]
Awesome! There is no way where we could fetch this list right? (at least I couldn't find any)

**Comment by jessedijkstra** [comment]
@sn3p auto fetch this list from the interwebz?

**Comment by sn3p** [comment]
> @sn3p auto fetch this list from the interwebz?

I mean from a maintained lib or mix

**Comment by fatboypunk** [comment]
> I mean from a maintained lib or mix

We could make one?

**Comment by jessedijkstra** [comment]
@sn3p @fatboypunk If it is meaningful (currently it is not since it's only maintained because of backwards compatibility) we could create a JSON gist where the it is fetched from.

**Review by sn3p — APPROVED** [review]

**Pull request merged**
